# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Sayson
email: masayson@gmail.com
linkedin: https://www.linkedin.com/in/mark-sayson-87208748
description: Notes on software development and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marksayson.com" # the base hostname & protocol for your site
github_username:  msayson
paginate: 8 # maximum number of blog posts per page

# Build settings
markdown: kramdown

# Google Analytics settings
google_analytics_tracking_id: UA-80369609-1

gems:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
