# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.marksayson.com" # the base hostname & protocol for your site
enforce_ssl: www.marksayson.com   # enforce SSL for site

# Site variables
title: Mark Sayson
email: masayson@gmail.com
linkedin: https://www.linkedin.com/in/mark-sayson-87208748
description: Notes on software development, technology, and life.
github_username:  msayson

# Pagination settings
paginate: 8 # maximum number of blog posts per page
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Google Analytics 4 settings
ga_tracking: G-0X2FJYXEPK

# Deprecated Google "Universal Analytics" settings
google_analytics_tracking_id: UA-80369609-1

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
